### ISSUE TITLE
Template no longer works with recent Typst versions (0.14) due to language changes

### ISSUE THREAD

**Issue by ruboerner** [andreasKroepelin/typst-notebook#2]
Hello Andreas,

first of all, thank you for this repository. I used the typst-notebook template about two years ago (with an older Typst version at the time) and was impressed by the design and overall workflow - it was a pleasure to work with.

Recently, I wanted to pick up the notebook again for new work. Unfortunately, I found that the template no longer functions with current Typst versions (I am using Typst 0.14). It appears that language changes introduced since Typst 0.12 have broken several parts of the template, leading to compilation errors and preventing it from working out of the box.

I fully understand that Typst has undergone significant evolution and that maintaining compatibility across breaking language changes can be nontrivial. I mainly wanted to report this in case you are interested in updating the template, documenting the supported Typst version more explicitly, or marking the repository as incompatible with newer releases.

Thank you again for sharing this work - it was excellent, and I hope to be able to use it again in the future.

Best regards,
Ralph

**Comment by andreasKroepelin** [comment]
Hi Ralph, great that this template was useful to you! To be honest, I ended up never really using it myself so I also neglected maintenance. I'm open to updating the template for the current Typst version and I very much welcome anyone's contributions there. For full disclosure, it is not very high on my priority list right now.
